add_newline = true
palette = "catppuccin_mocha"

format = """
$directory$fill$git_branch$git_status$rust$python$golang$aws$gcloud$cmd_duration
$character"""


[fill]
symbol = " "

[directory]
style = "bold blue"
format = "[$path]($style) "
truncation_length = 1
truncate_to_repo = false
truncation_symbol = "~/"

[git_branch]
symbol = " "
style = "bold mauve"
format = "on [$symbol$branch]($style) "

[rust]
symbol = "🦀 "
style = "bold red"
format = "is [$symbol($version)]($style) "

[python]
symbol = "  "
style = "bold green"
format = "via [$symbol($version)]($style) "


[cmd_duration]
min_time = 500
style = "bold yellow"
format = "󱎫 [$duration]($style) "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[gcloud]
symbol = "${GCP_SYMBOL-}"
format = "[$symbol$account]($style) "
disabled = false
style = "bold sky"

#[gcloud.project_aliases]
# project-id = alias



[aws]
format = "on [$symbol$profile](bold $style) [($region)](italic $style) "
symbol = "󰸏 "
style = "peach"
disabled = false

[aws.region_aliases]
ap-southeast-1 = "󰇧 SG"
ap-southeast-2 = "󰇧 AU"
ap-northeast-1 = "󰇧 TYO"
ap-northeast-2 = "󰇧 SEL"
us-east-1 = "󰇧 VA"
us-east-2 = "󰇧 OH"
us-west-1 = "󰇧 CA"
us-west-2 = "󰇧 OR"
eu-central-1 = "󰇧 FRA"
eu-west-1 = "󰇧 IRE"

[golang]
format = "[ ](bold cyan)"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
