add_newline = true
palette = "catppuccin_mocha"
command_timeout = 1000

format = """
$directory$fill$git_branch$git_status$rust$python$golang$aws$gcloud$cmd_duration
$character"""

[fill]
symbol = " "

[directory]
style = "bold cyan"
format = "[$path]($style) "
truncation_length = 10
truncate_to_repo = false
truncation_symbol = ".../"

[git_commit]
tag_symbol = "  "

[git_branch]
symbol = " "
style = "bold magenta"
format = "on [$symbol$branch]($style) "

[rust]
symbol = "🦀 "
style = "bold red"
format = "is [$symbol($version)]($style) "

[python]
symbol = "🐍 "
style = "bold yellow"
format = "via [$symbol($version)]($style) "

[cmd_duration]
min_time = 500
style = "bold yellow"
format = "took [$duration]($style) "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

#[os]
#disabled = false
#style = "bold white"

#[os.symbols]
#Macos = "󰀵 "
#Ubuntu = "󰕈 "
#Arch = "󰣇 "

#[character]
#success_symbol = "[󱞩](bold #a6e3a1)"
#error_symbol = "[󱞩](bold #f38ba8)"

#[character]
#success_symbol = "[󰊠 ](bold green)"
#error_symbol = "[󰊠 ](bold red)"

#[directory]
#style = "bold #89b4fa"
#format = "[$path]($style)[$read_only]($read_only_style) "
#truncation_length = 3
#truncate_to_repo = true

#[character]
#vicmd_symbol = "[N] >>>"
#success_symbol = "[➜](bold green)"

#[directory.substitutions]
#"~/tests/starship-custom" = "work-project"

[gcloud]
format = '[$symbol$account]($style) '
symbol = " "
disabled = false

[aws]
format = "on [$symbol$profile](bold #ff9900) [($region)](italic #ff9900) "
symbol = "󰸏 "
disabled = false

[aws.region_aliases]
ap-southeast-1 = "󰇧 SG"
ap-southeast-2 = "󰇧 AU"
ap-northeast-1 = "󰇧 TYO"
ap-northeast-2 = "󰇧 SEL"
us-east-1 = "󰇧 VA"
us-east-2 = "󰇧 OH"
us-west-1 = "󰇧 CA"
us-west-2 = "󰇧 OR"
eu-central-1 = "󰇧 FRA"
eu-west-1 = "󰇧 IRE"

[golang]
format = "[ ](bold cyan)"

[kubernetes]
symbol = "☸ "
disabled = false
detect_files = ["Dockerfile"]
format = '[$symbol$context( \($namespace\))]($style) '

[[kubernetes.contexts]]
context_pattern = "arn:aws:eks:us-west-2:577926974532:cluster/zd-pvc-omer"
style = "green"
context_alias = "omerxx"
symbol = " "

[docker_context]
disabled = true

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
